/* Scan 01 — racing-digits font renderer (task T4, vision §5.6)
 *
 * Copyright 2026 Vadim Petrov
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * The glyph data (gRacingGlyphs, font_racing_data.c) is generated by
 * tools/fontgen_racing.py — the art there is the font source.
 */

#include <string.h>

#include "font_racing.h"

uint16_t RACING_TextWidth(const char *text)
{
    uint16_t width = 0;

    if (text == NULL)
        return 0;

    for (; *text; text++) {
        const char *p = strchr(gRacingGlyphOrder, *text);
        if (p == NULL)
            continue;
        width += gRacingGlyphAdvance[p - gRacingGlyphOrder];
        if (text[1] != 0)
            width++;                        /* 1 px spacing between glyphs */
    }
    return width;
}

void RACING_PrintNumber(uint8_t (*fb)[128], uint8_t line, uint8_t right_x,
                        const char *text)
{
    uint16_t total = RACING_TextWidth(text);
    uint16_t x;

    if (fb == NULL || text == NULL)
        return;

    x = (right_x >= total) ? (uint16_t)(right_x - total) : 0;

    for (; *text; text++) {
        const char *p = strchr(gRacingGlyphOrder, *text);
        if (p == NULL)
            continue;
        const RacingGlyph_t *g = &gRacingGlyphs[p - gRacingGlyphOrder];
        if (x + g->width > 128)
            break;                          /* never blit past the row (defensive) */
        for (int strip = 0; strip < 4; strip++)
            memcpy(fb[line + strip] + x, g->strips[strip], g->width);
        x += g->width + 1;                  /* advance + 1 px spacing */
    }
}
