#!/bin/bash
# Build the golden EEPROM fixture through the REAL firmware pack layer.
set -e
cd "$(dirname "$0")/.."
DEFS="-DENABLE_FEAT_SCAN01 -DENABLE_FMRADIO -DENABLE_NOAA -DENABLE_UART \
 -DENABLE_BIG_FREQ -DENABLE_SMALL_BOLD -DENABLE_TX1750 -DENABLE_KEEP_MEM_NAME \
 -DENABLE_WIDE_RX -DENABLE_NO_CODE_SCAN_TIMEOUT -DENABLE_AM_FIX \
 -DENABLE_SQUELCH_MORE_SENSITIVE -DENABLE_FASTER_CHANNEL_SCAN -DENABLE_RSSI_BAR \
 -DENABLE_SCAN_RANGES -DENABLE_FLASHLIGHT -DENABLE_CUSTOM_MENU_LAYOUT \
 -DENABLE_FEAT_F4HWN -DENABLE_FEAT_F4HWN_SCREENSHOT -DENABLE_FEAT_F4HWN_RX_TX_TIMER \
 -DENABLE_FEAT_F4HWN_SLEEP -DENABLE_FEAT_F4HWN_RESUME_STATE -DENABLE_FEAT_F4HWN_NARROWER \
 -DENABLE_FEAT_F4HWN_INV -DENABLE_FEAT_F4HWN_CTR -DENABLE_FEAT_F4HWN_CA"
gcc -Wall -Werror $DEFS -I. \
  tests/golden_pack.c tests/sim_stubs.c settings_pack.c pack_bandlock.c \
  -o /tmp/golden_pack
/tmp/golden_pack
